import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Navbar } from "@/ui/organisms/Navbar";
import { FooterWithSocialLinks } from "@/ui/organisms/Footer/Footer";
import { BluredGradients } from "@/ui/atoms/BluredGradients";
import { CustomCursor } from "@/ui/molecules/CustomCursor/CustomCursor";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Web Dev Agency",
	description: "Generated by create next app",
};

export default function LocaleLayout({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	return (
		<html lang={locale} suppressHydrationWarning>
			<body className={`${rubik.className}selection:bg-colorPrimary`}>
				<Providers>
					<div className="relative flex flex-col overflow-x-hidden">
						<Navbar locale={locale} />
						{/* <BluredGradients /> */}
						{children}
						<CustomCursor />
						<FooterWithSocialLinks />
					</div>
				</Providers>
			</body>
		</html>
	);
}
